package:
  name: stock_manager
  version: {{ load_setup_py_data().get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pyqt
    - opencv
    - numpy
    - gspread
    - oauth2client
    - pathlib
    - typing
    - qasync
    - qrcode
    - qtawesome
    - mysql-connector-python
    - prettytable

test:
  imports:
    - stock_manager
  requires:
    - pytest
    - pytest-qt
  source_files:
    - tests
  commands:
    - pytest -q

about:
  home: https://github.com/pcdshub/stock-management.git
  license: SLAC Open License
  license_file: LICENSE.md
  summary: "SLAC LCLS stock management application with QR code support and simple UI."
