name: PCDS Standard Testing

permissions:
  id-token: write
  contents: read

on:
  push:
  pull_request:
  release:
    types: [ created ]

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-standard.yml@master
    secrets: inherit
    with:
      package-name: "stock_manager"
      testing-extras: ""
      conda-testing-extras: ""
      pip-testing-extras: ""
      use-setuptools-scm: true
